endpoints:
  - https://httpbin.org/delay/2
  - https://httpbin.org/delay/2
  - https://httpbin.org/delay/2
  - https://google.com
  - https://fuga.cloud
  - http://httpbin.org/status/500
  - http://httpbin.org/status/404
  - https://yahoo.com
  - http:/example.com
pool_size: 5
time_out: 1
