version: "3"
services:
  fuga-exporter:
    build:
      context: exporter
    container_name: fuga-exporter
    hostname: fuga-exporter
    ports:
      - "8789:8789"
    volumes:
      - .:/usr/src/app/fuga-exporter
    environment:
      - OMNICONF_YAML_FILENAME=/usr/src/app/fuga-exporter/configuration.yaml
    command: python __main__.py
    depends_on:
      - redis
  es-gatherer:
    build:
      context: elasticsearch
    container_name: es-gatherer
    hostname: es-gatherer
    environment:
      - OMNICONF_YAML_FILENAME=/usr/src/app/fuga-exporter/es-gatherer/configuration.yaml
    command: python __main__.py
    depends_on:
      - elasticsearch
      - redis
    volumes:
      - .:/usr/src/app/fuga-exporter
  prom-gatherer:
    build:
      context: prometheus
    container_name: prom-gatherer
    hostname: prom-gatherer
    environment:
      - OMNICONF_YAML_FILENAME=/usr/src/app/fuga-exporter/prom-gatherer/configuration.yaml
    command: python __main__.py
    depends_on:
      - prometheus
      - redis
    volumes:
      - .:/usr/src/app/fuga-exporter


  redis:
    image: redis:4-alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
  prometheus:
    # image: prom/prometheus
    build:
      context: .
    hostname: prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
  elasticsearch:
    image: elasticsearch:6.4.2
    hostname: elasticsearch
    container_name: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
  prometheus-redis:
    image: oliver006/redis_exporter
    hostname: prometheus-redis
    container_name: prometheus-redis
    environment:
      - REDIS_ADDR=redis://redis
    ports:
      - "9121:9121"
  prometheus-test:
    build:
      context: .
      dockerfile: Dockerfile-test
    hostname: prometheus-test
    container_name: prometheus-test
    ports:
      - "9091:9090"
    depends_on:
      - fuga-exporter
  grafana:
    image: grafana/grafana
    hostname: grafana
    container_name: grafana
    ports:
      - "3000:3000"
